# Databricks Apps runtime configuration
# Resources and scopes are bound automatically by deploy.sh.
#
# Resource bindings (set by deploy.sh via Apps API):
#   sql-warehouse             → DATABRICKS_WAREHOUSE_ID
#   serving-endpoint          → DATABRICKS_SERVING_ENDPOINT
#   serving-endpoint-fast     → DATABRICKS_SERVING_ENDPOINT_FAST
#   serving-endpoint-embedding → DATABRICKS_EMBEDDING_ENDPOINT
#
# User authorization scopes (set by deploy.sh via Apps API):
#   sql, catalog.tables:read, catalog.schemas:read,
#   catalog.catalogs:read, files.files, dashboards.genie
#
# Auth model:
#   - SQL queries run as the logged-in user (OBO via x-forwarded-access-token)
#   - Genie Space management uses user OBO by default (configurable in Settings)
#   - Model Serving, Workspace API run as the app service principal
#   - Background pipeline tasks fall back to service principal
#
# Lakebase Autoscale is self-provisioned at startup using the platform-
# injected service principal credentials (DATABRICKS_CLIENT_ID/SECRET/HOST).
# No secret scope or DATABASE_URL binding needed.
#
# Runtime DB auth mode is injected by deploy.sh at deploy-time:
#   LAKEBASE_AUTH_MODE=native_password (default) OR oauth
# In native_password mode, deploy.sh also injects:
#   LAKEBASE_NATIVE_USER, LAKEBASE_NATIVE_PASSWORD

command:
  - "sh"
  - "scripts/start.sh"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABRICKS_SERVING_ENDPOINT
    valueFrom: serving-endpoint
  - name: DATABRICKS_SERVING_ENDPOINT_FAST
    valueFrom: serving-endpoint-fast
  - name: DATABRICKS_EMBEDDING_ENDPOINT
    valueFrom: serving-endpoint-embedding
