# Databricks Apps configuration
# Maps app resources to environment variables consumed by the Next.js backend.
#
# Required app resources (configure in Databricks App UI):
#   1. SQL Warehouse — resource key: "sql-warehouse"
#
# For production, replace the DATABASE_URL value with a secret reference:
#   valueFrom: db-secret
# And add a Secret resource in the App UI with the connection string.

command:
  - "bash"
  - "-c"
  - "npx prisma db push --skip-generate && node .next/standalone/server.js"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABASE_URL
    value: "postgresql://databricks_inspire:npg_lT3MW5OKudfE@ep-curly-silence-d1wsggbw-pooler.database.us-west-2.cloud.databricks.com/databricks_postgres?sslmode=require"
  - name: LAKEBASE_CATALOG
    value: main
