# Databricks Apps configuration
# Maps app resources to environment variables consumed by the Next.js backend.
#
# Required app resources (configure in Databricks App UI):
#   1. SQL Warehouse — resource key: "sql-warehouse"
#   2. Secret — resource key: "db-secret" (Databricks secret scope containing DATABASE_URL)
#
# To set up the secret:
#   databricks secrets create-scope inspire-secrets
#   databricks secrets put-secret inspire-secrets DATABASE_URL --string-value "postgresql://..."
#   Then add a Secret resource in the App UI with scope "inspire-secrets", key "DATABASE_URL",
#   and resource key "db-secret".

command:
  - "bash"
  - "-c"
  - "npx prisma db push --skip-generate && node .next/standalone/server.js"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABASE_URL
    valueFrom: db-secret
  - name: LAKEBASE_CATALOG
    value: main
