/**
 * Notebook deployment -- generates SQL notebooks and deploys them
 * to the Databricks workspace via the Workspace REST API.
 */

import { importNotebook, mkdirs } from "@/lib/dbx/workspace";
import type { PipelineRun, UseCase } from "@/lib/domain/types";
import { groupByDomain } from "@/lib/domain/scoring";

interface NotebookDeployResult {
  count: number;
  path: string;
  notebooks: Array<{
    name: string;
    path: string;
  }>;
}

/**
 * Generate and deploy SQL notebooks for each use case.
 * Organised by domain in the workspace.
 */
export async function generateNotebooks(
  run: PipelineRun,
  useCases: UseCase[]
): Promise<NotebookDeployResult> {
  const basePath = run.config.generationPath.replace(
    /^\.?\/?/,
    `/Workspace/inspire_gen/${run.config.businessName.replace(/\s+/g, "_")}/`
  );

  // Create base directory
  await mkdirs(basePath);

  const grouped = groupByDomain(useCases);
  const deployed: Array<{ name: string; path: string }> = [];

  for (const [domain, cases] of Object.entries(grouped)) {
    const domainPath = `${basePath}${domain}`;
    await mkdirs(domainPath);

    for (const uc of cases) {
      if (!uc.sqlCode) continue; // skip use cases without SQL

      const notebookName = `${uc.id}_${uc.name.replace(/[^a-zA-Z0-9]/g, "_").substring(0, 50)}`;
      const notebookPath = `${domainPath}/${notebookName}`;

      const content = generateNotebookContent(run, uc);

      try {
        await importNotebook({
          path: notebookPath,
          language: "SQL",
          content,
          overwrite: true,
        });
        deployed.push({ name: notebookName, path: notebookPath });
      } catch (error) {
        console.warn(
          `[notebooks] Failed to deploy ${notebookName}:`,
          error
        );
      }
    }
  }

  return {
    count: deployed.length,
    path: basePath,
    notebooks: deployed,
  };
}

/**
 * Generate SQL notebook content for a single use case.
 */
function generateNotebookContent(
  run: PipelineRun,
  uc: UseCase
): string {
  return `-- Databricks notebook source
-- MAGIC %md
-- MAGIC # ${uc.name}
-- MAGIC
-- MAGIC **Domain:** ${uc.domain} / ${uc.subdomain}
-- MAGIC **Type:** ${uc.type} | **Technique:** ${uc.analyticsTechnique}
-- MAGIC
-- MAGIC ## Business Statement
-- MAGIC ${uc.statement}
-- MAGIC
-- MAGIC ## Solution
-- MAGIC ${uc.solution}
-- MAGIC
-- MAGIC ## Business Value
-- MAGIC ${uc.businessValue}
-- MAGIC
-- MAGIC **Beneficiary:** ${uc.beneficiary} | **Sponsor:** ${uc.sponsor}
-- MAGIC
-- MAGIC **Score:** ${Math.round(uc.overallScore * 100)}% (Priority: ${Math.round(uc.priorityScore * 100)}%, Feasibility: ${Math.round(uc.feasibilityScore * 100)}%, Impact: ${Math.round(uc.impactScore * 100)}%)
-- MAGIC
-- MAGIC ---

-- COMMAND ----------

-- Generated by Databricks Inspire AI for ${run.config.businessName}
-- Tables: ${uc.tablesInvolved.join(", ")}

${uc.sqlCode}
`;
}
